include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_specify_types: true
    omit_local_variable_types: false
    constant_identifier_names: true
    sort_child_properties_last: true
    unnecessary_brace_in_string_interps: true
    await_only_futures: true
    avoid_classes_with_only_static_members: false
    sort_constructors_first: true
    prefer_const_constructors : false